//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.ReportSource;
using CrystalDecisions.Shared;
using System;
using System.ComponentModel;



public class cr_guard_deployment_schedule_report : ReportClass {
    
    public cr_guard_deployment_schedule_report() {
    }
    
    public override string ResourceName {
        get {
            return "cr_guard_deployment_schedule_report.rpt";
        }
        set {
            // Do nothing
        }
    }
    
    public override bool NewGenerator {
        get {
            return true;
        }
        set {
            // Do nothing
        }
    }
    
    public override string FullResourceName {
        get {
            return "cr_guard_deployment_schedule_report.rpt";
        }
        set {
            // Do nothing
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section1 {
        get {
            return this.ReportDefinition.Sections[0];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section2 {
        get {
            return this.ReportDefinition.Sections[1];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section3 {
        get {
            return this.ReportDefinition.Sections[2];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section4 {
        get {
            return this.ReportDefinition.Sections[3];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section5 {
        get {
            return this.ReportDefinition.Sections[4];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_QueryName {
        get {
            return this.DataDefinition.ParameterFields[0];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_record_guid {
        get {
            return this.DataDefinition.ParameterFields[1];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_guard_number {
        get {
            return this.DataDefinition.ParameterFields[2];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_id {
        get {
            return this.DataDefinition.ParameterFields[3];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_start_date {
        get {
            return this.DataDefinition.ParameterFields[4];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_end_date {
        get {
            return this.DataDefinition.ParameterFields[5];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_created_by {
        get {
            return this.DataDefinition.ParameterFields[6];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_active {
        get {
            return this.DataDefinition.ParameterFields[7];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_active_deployment {
        get {
            return this.DataDefinition.ParameterFields[8];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_date {
        get {
            return this.DataDefinition.ParameterFields[9];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_type {
        get {
            return this.DataDefinition.ParameterFields[10];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_branch_name {
        get {
            return this.DataDefinition.ParameterFields[11];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_id {
        get {
            return this.DataDefinition.ParameterFields[12];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_rate {
        get {
            return this.DataDefinition.ParameterFields[13];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_code {
        get {
            return this.DataDefinition.ParameterFields[14];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_location {
        get {
            return this.DataDefinition.ParameterFields[15];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_guard_auto_id {
        get {
            return this.DataDefinition.ParameterFields[16];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_guard_name {
        get {
            return this.DataDefinition.ParameterFields[17];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_firearm_serial {
        get {
            return this.DataDefinition.ParameterFields[18];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_number_of_ammunitions {
        get {
            return this.DataDefinition.ParameterFields[19];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_shift_type {
        get {
            return this.DataDefinition.ParameterFields[20];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_is_leave_day_for_guard {
        get {
            return this.DataDefinition.ParameterFields[21];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_is_public_holiday {
        get {
            return this.DataDefinition.ParameterFields[22];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_is_weekend {
        get {
            return this.DataDefinition.ParameterFields[23];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_check_public_holiday {
        get {
            return this.DataDefinition.ParameterFields[24];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_payment_month {
        get {
            return this.DataDefinition.ParameterFields[25];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_days_worked {
        get {
            return this.DataDefinition.ParameterFields[26];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_over_time_days_worked {
        get {
            return this.DataDefinition.ParameterFields[27];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_days_absent {
        get {
            return this.DataDefinition.ParameterFields[28];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_total_advance_in_month {
        get {
            return this.DataDefinition.ParameterFields[29];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_total_arrears_in_month {
        get {
            return this.DataDefinition.ParameterFields[30];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_special_cash_additions {
        get {
            return this.DataDefinition.ParameterFields[31];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_residential_cost {
        get {
            return this.DataDefinition.ParameterFields[32];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_uniform_costs {
        get {
            return this.DataDefinition.ParameterFields[33];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_local_service_tax_cost {
        get {
            return this.DataDefinition.ParameterFields[34];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_other_penalties_cost {
        get {
            return this.DataDefinition.ParameterFields[35];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_other_refunds {
        get {
            return this.DataDefinition.ParameterFields[36];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_period_id {
        get {
            return this.DataDefinition.ParameterFields[37];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_details_id {
        get {
            return this.DataDefinition.ParameterFields[38];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_public_holiday_name {
        get {
            return this.DataDefinition.ParameterFields[39];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_public_holiday_date {
        get {
            return this.DataDefinition.ParameterFields[40];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_name {
        get {
            return this.DataDefinition.ParameterFields[41];
        }
    }
}

[System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
public class Cachedcr_guard_deployment_schedule_report : Component, ICachedReport {
    
    public Cachedcr_guard_deployment_schedule_report() {
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual bool IsCacheable {
        get {
            return true;
        }
        set {
            // 
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual bool ShareDBLogonInfo {
        get {
            return false;
        }
        set {
            // 
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual System.TimeSpan CacheTimeOut {
        get {
            return CachedReportConstants.DEFAULT_TIMEOUT;
        }
        set {
            // 
        }
    }
    
    public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CreateReport() {
        cr_guard_deployment_schedule_report rpt = new cr_guard_deployment_schedule_report();
        rpt.Site = this.Site;
        return rpt;
    }
    
    public virtual string GetCustomizedCacheKey(RequestContext request) {
        String key = null;
        // // The following is the code used to generate the default
        // // cache key for caching report jobs in the ASP.NET Cache.
        // // Feel free to modify this code to suit your needs.
        // // Returning key == null causes the default cache key to
        // // be generated.
        // 
        // key = RequestContext.BuildCompleteCacheKey(
        //     request,
        //     null,       // sReportFilename
        //     this.GetType(),
        //     this.ShareDBLogonInfo );
        return key;
    }
}
