//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.ReportSource;
using CrystalDecisions.Shared;
using System;
using System.ComponentModel;



public class Guard_profilerfinance_employee_nssf_report : ReportClass {
    
    public Guard_profilerfinance_employee_nssf_report() {
    }
    
    public override string ResourceName {
        get {
            return "Guard_profiler.finance_employee_nssf_report.rpt";
        }
        set {
            // Do nothing
        }
    }
    
    public override bool NewGenerator {
        get {
            return true;
        }
        set {
            // Do nothing
        }
    }
    
    public override string FullResourceName {
        get {
            return "Guard_profiler.finance_employee_nssf_report.rpt";
        }
        set {
            // Do nothing
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section1 {
        get {
            return this.ReportDefinition.Sections[0];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section2 {
        get {
            return this.ReportDefinition.Sections[1];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section3 {
        get {
            return this.ReportDefinition.Sections[2];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section4 {
        get {
            return this.ReportDefinition.Sections[3];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.CrystalReports.Engine.Section Section5 {
        get {
            return this.ReportDefinition.Sections[4];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_QueryName {
        get {
            return this.DataDefinition.ParameterFields[0];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_guard_number {
        get {
            return this.DataDefinition.ParameterFields[1];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_period_id {
        get {
            return this.DataDefinition.ParameterFields[2];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_station_code {
        get {
            return this.DataDefinition.ParameterFields[3];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_station_name {
        get {
            return this.DataDefinition.ParameterFields[4];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_date_from {
        get {
            return this.DataDefinition.ParameterFields[5];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_deploy_date_to {
        get {
            return this.DataDefinition.ParameterFields[6];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_code {
        get {
            return this.DataDefinition.ParameterFields[7];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_branch_name {
        get {
            return this.DataDefinition.ParameterFields[8];
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public CrystalDecisions.Shared.IParameterField Parameter_client_name {
        get {
            return this.DataDefinition.ParameterFields[9];
        }
    }
}

[System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
public class CachedGuard_profilerfinance_employee_nssf_report : Component, ICachedReport {
    
    public CachedGuard_profilerfinance_employee_nssf_report() {
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual bool IsCacheable {
        get {
            return true;
        }
        set {
            // 
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual bool ShareDBLogonInfo {
        get {
            return false;
        }
        set {
            // 
        }
    }
    
    [Browsable(false)]
    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public virtual System.TimeSpan CacheTimeOut {
        get {
            return CachedReportConstants.DEFAULT_TIMEOUT;
        }
        set {
            // 
        }
    }
    
    public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CreateReport() {
        Guard_profilerfinance_employee_nssf_report rpt = new Guard_profilerfinance_employee_nssf_report();
        rpt.Site = this.Site;
        return rpt;
    }
    
    public virtual string GetCustomizedCacheKey(RequestContext request) {
        String key = null;
        // // The following is the code used to generate the default
        // // cache key for caching report jobs in the ASP.NET Cache.
        // // Feel free to modify this code to suit your needs.
        // // Returning key == null causes the default cache key to
        // // be generated.
        // 
        // key = RequestContext.BuildCompleteCacheKey(
        //     request,
        //     null,       // sReportFilename
        //     this.GetType(),
        //     this.ShareDBLogonInfo );
        return key;
    }
}
